server:
  port: 8761  
eureka:
  instance:
    hostname: eureka-us
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://eureka-us:8761/eureka,http://eureka-uk:8762/eureka
    registerWithEureka: false
    fetchRegistry: false  