spring:
  profiles:
    active: uk
  application:
    name: uk-test-service
eureka:
  instance:
      lease-renewal-interval-in-seconds: 10
  client:
    region: global
    register-with-eureka: true
    fetch-registry: true
    service-url:
      uk_zone: http://eureka-uk:8762/eureka
      us_zone: http://eureka-us:8761/eureka
    availability-zones:
      global: uk_zone,us_zone