spring:
  application:
    name: test-service
server:
  port: 9001
eureka:
  instance:
      lease-renewal-interval-in-seconds: 10
  client:
    region: UK
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-uk:8762/eureka

