spring:
  profiles:
    active: us
  application:
    name: gateway  
zuul:
  routes:
    test-service:
      path: /gateway/test/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      serviceId: test-service
eureka:
  client:
    region: global
    prefer-same-zone-eureka: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      us_zone: http://eureka-us:8761/eureka
      uk_zone: http://eureka-uk:8762/eureka
    availability-zones:
      global: us_zone