server:
  port: 8762
eureka:
  instance:
    hostname: eureka-uk
    appname: eureka-cluster
  client:
    service-url:
      defaultZone: http://eureka-us:8761/eureka,http://eureka-uk:8762/eureka
    registerWithEureka: false
    fetchRegistry: false  