spring:
  profiles:
    active: us
  application:
    name: us-test-service
eureka:
  instance:
      lease-renewal-interval-in-seconds: 10
  client:
    region: global
    register-with-eureka: true
    fetch-registry: true
    service-url:
      us_zone: http://eureka-us:8761/eureka
      uk_zone: http://eureka-uk:8762/eureka
    availability-zones:
      global: us_zone,uk_zone